import { useRef, useState, type FormEvent } from 'react';
import { ShieldCheck, LockKeyhole, Mail, ArrowRight, ArrowLeft, Landmark, Eye, EyeOff, CheckCircle2, Fingerprint, Info, ExternalLink } from 'lucide-react';
import { useAuth, roleLabels } from '@/context/AuthContext';

function BrandMark(){return <div className="login-seal"><Landmark size={30}/></div>}

export default function Login(){
 const {step,error,verifyCredentials,verifyOtp,reset,pendingUser}=useAuth();
 const [email,setEmail]=useState('rajesh.kumar@gov.in'); const [password,setPassword]=useState('demo1234'); const [showPassword,setShowPassword]=useState(false); const [otp,setOtp]=useState(['','','','','','']); const refs=useRef<(HTMLInputElement|null)[]>([]);
 const credentials=(e:FormEvent)=>{e.preventDefault();verifyCredentials(email,password)};
 const otpChange=(i:number,v:string)=>{if(!/^\d?$/.test(v))return;const n=[...otp];n[i]=v;setOtp(n);if(v&&i<5)refs.current[i+1]?.focus()};
 const otpKey=(i:number,e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Backspace'&&!otp[i]&&i>0)refs.current[i-1]?.focus()};
 const otpPaste=(e:React.ClipboardEvent)=>{e.preventDefault();const p=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);const n=[...otp];p.split('').forEach((x,i)=>n[i]=x);setOtp(n);if(p)refs.current[Math.min(p.length,5)]?.focus()};
 return <div className="min-h-screen bg-[#eef2f6] text-[#102a43] flex flex-col">
   <div className="h-1 bg-gradient-to-r from-[#f2a900] via-white to-[#138808]"/>
   <header className="bg-white border-b border-slate-200 px-5 lg:px-10 py-3 flex items-center justify-between">
     <div className="flex items-center gap-3"><BrandMark/><div><div className="text-sm font-bold tracking-tight">Government of India</div><div className="text-[10px] text-slate-500">National Land Acquisition & Management System</div></div></div>
     <div className="hidden sm:flex items-center gap-4 text-[10px] text-slate-500"><span>Authorized Officer Portal</span><span className="px-2 py-1 border border-amber-200 bg-amber-50 text-amber-700 uppercase tracking-wider">SIH Demonstration</span></div>
   </header>
   <main className="flex-1 flex items-center justify-center p-5 lg:p-10">
     <div className="w-full max-w-6xl grid lg:grid-cols-[1.05fr_.95fr] bg-white border border-slate-200 shadow-[0_18px_50px_rgba(15,42,67,.10)] min-h-[620px]">
       <section className="hidden lg:flex relative overflow-hidden bg-[#102a43] text-white p-10 xl:p-14 flex-col justify-between">
         <div className="absolute inset-0 opacity-[.08] pointer-events-none"><div className="absolute -right-32 -top-32 w-[520px] h-[520px] rounded-full border border-white/70"/><div className="absolute -right-12 -top-12 w-[280px] h-[280px] rounded-full border border-white/50"/><div className="absolute right-16 top-16 w-28 h-28 rounded-full border border-white/40"/></div>
         <div className="relative"><div className="inline-flex items-center gap-2 border border-white/15 bg-white/5 px-3 py-1.5 text-[10px] uppercase tracking-[.18em] text-slate-300"><ShieldCheck size={13}/> Secure government workspace</div><h2 className="text-4xl xl:text-5xl font-semibold leading-[1.08] mt-8 max-w-xl">One national view of the <span className="text-[#f2c14e]">land acquisition lifecycle.</span></h2><p className="text-sm xl:text-base text-slate-300 leading-7 max-w-lg mt-6">Coordinate proposals, parcels, statutory notifications, awards, compensation, possession and rehabilitation through a single role-aware platform.</p></div>
         <div className="relative grid grid-cols-3 gap-3 mt-10"><div className="border border-white/10 bg-white/5 p-4"><div className="text-xl font-semibold">09</div><div className="text-[10px] text-slate-400 mt-1">Lifecycle stages</div></div><div className="border border-white/10 bg-white/5 p-4"><div className="text-xl font-semibold">GIS</div><div className="text-[10px] text-slate-400 mt-1">Parcel intelligence</div></div><div className="border border-white/10 bg-white/5 p-4"><div className="text-xl font-semibold">RBAC</div><div className="text-[10px] text-slate-400 mt-1">Access controls</div></div></div>
         <div className="relative flex items-center gap-2 text-[10px] text-slate-400 mt-8"><Info size={13}/> Prototype environment · Do not use for production government records.</div>
       </section>
       <section className="p-7 sm:p-10 xl:p-14 flex items-center">
         <div className="w-full max-w-md mx-auto">
           {step==='credentials' ? <div className="animate-fade-in"><div className="mb-8"><div className="lg:hidden flex items-center gap-3 mb-7"><BrandMark/><div><b className="text-sm">Government of India</b><div className="text-[10px] text-slate-500">National Land Acquisition & Management System</div></div></div><div className="text-[10px] uppercase tracking-[.18em] text-[#1e4f73] font-bold">Authorized officer access</div><h1 className="text-3xl font-semibold mt-2 tracking-tight">Sign in to NLAMS</h1><p className="text-sm text-slate-500 mt-2 leading-6">Use your official credentials to continue to the secure acquisition workspace.</p></div>
             <form onSubmit={credentials} className="space-y-5"><label className="block"><span className="text-xs font-semibold text-slate-700">Official email address</span><div className="relative mt-1.5"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="gov-input w-full pl-10 pr-3 py-3.5 text-sm" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@gov.in" required/></div></label><label className="block"><div className="flex justify-between"><span className="text-xs font-semibold text-slate-700">Password</span><button type="button" className="text-[10px] text-[#1e4f73] font-semibold">Forgot password?</button></div><div className="relative mt-1.5"><LockKeyhole className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="gov-input w-full pl-10 pr-11 py-3.5 text-sm" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" required/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div className="p-3 border border-red-200 bg-red-50 text-xs text-red-700">{error}</div>}<button className="w-full gov-btn-primary py-3.5 text-sm font-bold flex items-center justify-center gap-2 group">Continue securely <ArrowRight size={16} className="group-hover:translate-x-0.5 transition"/></button></form>
             <div className="mt-6 border border-slate-200 bg-slate-50 p-4"><div className="flex items-start gap-3"><Fingerprint size={19} className="text-[#1e4f73] mt-0.5"/><div><b className="text-xs text-[#102a43]">Two-factor verification enabled</b><p className="text-[10px] text-slate-500 mt-1 leading-5">A verification code is required after credential validation. This demonstration uses a fixed test OTP.</p></div></div></div><div className="mt-5 flex items-center justify-between text-[10px] text-slate-400"><span>Accessibility</span><span>Help & support</span><span>Privacy & security</span></div><div className="mt-6 text-[10px] text-slate-400 flex gap-1 items-center"><ExternalLink size={11}/> Demo credentials are available only for this SIH prototype.</div>
           </div> : <div className="animate-fade-in"><button onClick={reset} className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-[#102a43] mb-8"><ArrowLeft size={14}/> Back to sign in</button><div className="w-12 h-12 bg-[#102a43] text-[#f2c14e] flex items-center justify-center mb-5"><ShieldCheck size={25}/></div><div className="text-[10px] uppercase tracking-[.18em] text-[#1e4f73] font-bold">Step 2 of 2</div><h1 className="text-3xl font-semibold mt-2">Verify your identity</h1><p className="text-sm text-slate-500 mt-2 leading-6">Enter the six-digit verification code for the registered officer account.</p>{pendingUser&&<div className="mt-5 border border-slate-200 bg-slate-50 p-3 text-xs"><b>{pendingUser.email}</b><div className="text-slate-500 mt-1">{roleLabels[pendingUser.role]} · {pendingUser.department}</div></div>}
             <form onSubmit={e=>{e.preventDefault();verifyOtp(otp.join(''))}} className="mt-6"><div className="flex gap-2 sm:gap-3" onPaste={otpPaste}>{otp.map((d,i)=><input key={i} ref={el=>{refs.current[i]=el}} value={d} onChange={e=>otpChange(i,e.target.value)} onKeyDown={e=>otpKey(i,e)} inputMode="numeric" maxLength={1} className="w-11 sm:w-12 h-14 text-center text-xl font-semibold border border-slate-300 bg-white focus:outline-none focus:border-[#1e4f73] focus:ring-2 focus:ring-blue-100"/> )}</div>{error&&<div className="mt-4 p-3 border border-red-200 bg-red-50 text-xs text-red-700">{error}</div>}<button className="w-full gov-btn-primary py-3.5 text-sm font-bold flex items-center justify-center gap-2 mt-6">Verify & enter <ArrowRight size={16}/></button></form><div className="mt-5 flex gap-2 items-start text-[10px] text-slate-500"><CheckCircle2 size={14} className="text-emerald-600 shrink-0"/> Demo OTP: <b>428913</b>. In production this would be delivered through an approved authentication service.</div>
           </div>}
         </div>
       </section>
     </div>
   </main>
   <footer className="px-5 lg:px-10 py-4 text-[10px] text-slate-500 flex flex-wrap gap-x-6 gap-y-2 justify-center border-t border-slate-200 bg-white">Government of India · National Land Acquisition & Management System · SIH 2026 demonstration · Authorized access only</footer>
 </div>
}
